In [3]:
import numpy as np
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [6]:
b=arr

In [11]:
arr[b]

array([11, 12, 13, 14, 15])

In [23]:
arr[arr%2==0]

array([0, 0, 0, 0, 0, 0, 0])