In [1]:
import numpy as np
a=[2,4,6,5,2,7,89,9]
arr=np.array(a)
arr

array([ 2,  4,  6,  5,  2,  7, 89,  9])

In [2]:
np.min(arr)

2

In [3]:
np.max(arr)

89

In [4]:
np.cos(arr)

array([-0.41614684, -0.65364362,  0.96017029,  0.28366219, -0.41614684,
        0.75390225,  0.51017704, -0.91113026])

In [5]:
np.sin(arr)

array([ 0.90929743, -0.7568025 , -0.2794155 , -0.95892427,  0.90929743,
        0.6569866 ,  0.86006941,  0.41211849])

In [6]:
np.sqrt(arr)

array([1.41421356, 2.        , 2.44948974, 2.23606798, 1.41421356,
       2.64575131, 9.43398113, 3.        ])

In [7]:
np.argmax(arr)

6

In [8]:
np.argmin(arr)

0

In [11]:
np.linspace(1,7,9)

array([1.  , 1.75, 2.5 , 3.25, 4.  , 4.75, 5.5 , 6.25, 7.  ])

In [20]:
np.random.seed(111)
a=np.random.randint(1,1000,21).reshape(7,3)
a

array([[853, 877, 981],
       [725,  87, 276],
       [682, 323, 119],
       [979, 809, 968],
       [954,   8, 269],
       [267, 450, 881],
       [729, 285, 271]])

In [21]:
np.sum(a)

11793

In [22]:
np.min(a)

8

In [23]:
np.max(a)

981

# another way

In [24]:
a.max()

981

In [26]:
np.cumsum(a)

array([  853,  1730,  2711,  3436,  3523,  3799,  4481,  4804,  4923,
        5902,  6711,  7679,  8633,  8641,  8910,  9177,  9627, 10508,
       11237, 11522, 11793])

In [28]:
np.min(a,axis=1)

array([853,  87, 119, 809,   8, 267, 271])

In [30]:
np.cumsum(a,axis=0)

array([[ 853,  877,  981],
       [1578,  964, 1257],
       [2260, 1287, 1376],
       [3239, 2096, 2344],
       [4193, 2104, 2613],
       [4460, 2554, 3494],
       [5189, 2839, 3765]])

In [33]:
np.random.shuffle(a)
a

array([[729, 285, 271],
       [725,  87, 276],
       [853, 877, 981],
       [267, 450, 881],
       [954,   8, 269],
       [979, 809, 968],
       [682, 323, 119]])

In [35]:
np.unique(a)

array([  8,  87, 119, 267, 269, 271, 276, 285, 323, 450, 682, 725, 729,
       809, 853, 877, 881, 954, 968, 979, 981])

In [37]:
np.unique(a).size

21

In [39]:
np.unique(a,return_index=True,return_counts=True)

(array([  8,  87, 119, 267, 269, 271, 276, 285, 323, 450, 682, 725, 729,
        809, 853, 877, 881, 954, 968, 979, 981]),
 array([13,  4, 20,  9, 14,  2,  5,  1, 19, 10, 18,  3,  0, 16,  6,  7, 11,
        12, 17, 15,  8], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=int64))