# zeros function

In [1]:
import numpy as np
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [6]:
a=np.zeros((7,9))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# ones function

In [7]:
a=np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [8]:
a=np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# eye function

In [9]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# diag function

In [14]:
a=np.diag([2,4,6,7])
a
np.diag(a)

array([2, 4, 6, 7])

# randint function

In [18]:
a=np.random.randint(1,10,8)
a

array([8, 6, 9, 9, 9, 3, 9, 6])

# rand function

In [20]:
a=np.random.rand(5)
a

array([0.31849753, 0.33706601, 0.64772857, 0.62035317, 0.50556022])

In [22]:
a=np.random.rand(2,3)
a

array([[0.5440892 , 0.92773136, 0.92470249],
       [0.47202115, 0.85100623, 0.28062703]])

# randn function

In [24]:
a=np.random.randn(4)
a

array([ 1.62061831,  1.35679055, -1.40959945, -1.81825705])

In [25]:
a=np.random.randn(2,3)
a

array([[-1.4544679 , -1.06101201, -1.14736375],
       [-0.18378712, -0.83891606, -0.16692613]])