In [1]:
import numpy as np
arr=np.arange(1,8)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [2]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [3]:
arr+2

array([3, 4, 5, 6, 7, 8, 9])

In [4]:
arr**2

array([ 1,  4,  9, 16, 25, 36, 49])

In [5]:
arr/0

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22252\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf])

In [6]:
arr//2

array([0, 1, 1, 2, 2, 3, 3], dtype=int32)

In [14]:
arr1=np.arange(1,7)
arr2=np.arange(7,13)


In [15]:
arr1+arr2

array([ 8, 10, 12, 14, 16, 18])

# working with 2d array

In [28]:
a=np.array([1,2,3,4,6,7]).reshape(3,2)
b=np.array([6,7,8,9,10,3.5]).reshape(3,2)



In [29]:
a+b

array([[ 7. ,  9. ],
       [11. , 13. ],
       [16. , 10.5]])

In [30]:
a*b

array([[ 6. , 14. ],
       [24. , 36. ],
       [60. , 24.5]])

In [32]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([6,7,8,9]).reshape(2,2)

In [33]:
a.dot(b)

array([[22, 25],
       [50, 57]])