# convert 1d to 2d

In [7]:
import numpy as np
arr=np.random.randint(1,50,12)
arr
arr.shape
arr=arr.reshape(2,6)
arr

array([[17, 26, 42, 21,  5, 44],
       [37, 31, 17, 42, 30, 28]])

# convert 2d to 1d

In [12]:
import numpy as np
arr=np.random.randint(1,50,12)
arr
arr.shape
arr=arr.reshape(2,6)
arr
arr=arr.reshape(12)
arr

array([ 1, 25,  8, 30, 26, 42,  3, 18, 46, 38, 20, 32])

# converting 1d to 3d

In [22]:
import numpy as np
a=[1,2,3,4,5,6,7,8]
arr=np.array(a)
arr.shape
arr=arr.reshape(2,2,2)
arr=arr.reshape(8)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])