In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a
b
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a
b
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
np.random.seed(122)
a=np.random.randint(1,50,9).reshape(3,3)
b=np.random.randint(51,100,9).reshape(3,3)
np.hstack((a,b))

array([[48, 27, 11, 93, 72, 82],
       [13, 17, 45, 92, 57, 65],
       [16, 35, 16, 86, 87, 82]])

In [12]:
np.random.seed(122)
a=np.random.randint(1,50,9).reshape(3,3)
b=np.random.randint(51,100,9).reshape(3,3)
np.vstack((a,b))

array([[48, 27, 11],
       [13, 17, 45],
       [16, 35, 16],
       [93, 72, 82],
       [92, 57, 65],
       [86, 87, 82]])